### ISSUE TITLE
Fatal Error: Cannot redeclare class WC_Product_Accommodation_Booking

### ISSUE THREAD

**Issue by cwuensche** [woocommerce/woocommerce-accommodation-bookings#105]
When I updated the WooCommerce Accommodation Bookings plugin today, it failed with the error

Fatal error: Cannot redeclare class WC_Product_Accommodation_Booking in /xxx/htdocs/xxx/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-product-accommodation-booking.php on line 151

I was able to "fix" this by going to woocommerce-bookings/includes/addons/accommodation-booking.php and commenting out the following code:
**
 * Simple structure for a MVP "working" accommodation product class.
 * Only to be used if the accommodtion plugin is missing so we don't fatal.
 */
	class WC_Product_Accommodation_Booking extends WC_Product_Skeleton_Booking {
		public function __construct( $product ) {
			$this->product_type = 'accommodation-booking';
			parent::__construct( $product );
		}

		public function bookings_addon_title() {
			return __( 'Accommodation booking', 'woocommerce-bookings' );
		}
	}

However, this is not a correct fix. I'm going to also figure out how to contact the plugin author of the WooCommerce Booking plugin to alert them about this error.

**Comment by larsmagnusherland** [comment]
Have the same issue if I upgrade to 1.0.8 version and the logs state the following:

PHP Fatal error:  Cannot declare class WC_Product_Accommodation_Booking, because the name is already in use

Doing the same as @cwuensche will solve it, but rather stay at 1.0.7 since both gives same issue with partial booking.

**Comment by jessepearson** [comment]
@cwuensche @larsmagnusherland Can you let us know what versions of WooCommerce and Bookings you are using? Bookings 1.10.0 has the below code in `includes/class-wc-product-class-loader.php`

```
/**
 * Bookings supports optional addons like the acommodation bookings plugin.
 * If these optional addons get removed but the data still exists, fatal errors can occur.
 * This class loader will load a dummy class for these bookings if the real one is not found.
 * This prevents purchasing of these products and prevents errors.
 * A notice will also be displayed to the user.
 */
class WC_Product_Class_Loader {
	function __construct() {
		add_action( 'plugins_loaded', array( $this, 'load_product_classes') );
	}

	public function load_product_classes() {
		if ( ! class_exists( 'WC_Product_Accommodation_Booking' ) ) {
			include_once( 'addons/accommodation-booking.php' );
		}
	}
}

new WC_Product_Class_Loader;
```

This file is loaded when the `plugins_loaded` hook fires, so there should never be a fatal error if Accommodations is active along with Bookings 1.10.0.

**Comment by jessepearson** [comment]
Just tested, because I had another report in a ticket. If Accommodations 1.0.8 is activated with a version of Bookings older than 1.10.0, it will create these fatal errors.

@bor0 Would we be able to add something into Accomm to be able to combat this problem? If users are using the WordPress updates page, I believe Accomm will update before Bookings, which would create these fatal errors.

**Comment by larsmagnusherland** [comment]
@jessepearson that is correct that I would need to use Accommodations 1.10.0 or higher for the error to be resolved. But trying to run this plugin together with WooCommerce 2.6.14 and Accomodations 1.9.12.
Many can't update to WooCommerce 3.0.X yet since it will cause issues for their stores, hence why I'm still running WooCommerce 2.6.14 and not the newest version.

**Comment by cwuensche** [comment]
@jessepearson I'm running WooCommerce 3.0.2, WooCommerce Bookings 1.9.12 and WooCommerce Bookings Accommodation Bookings 1.0.8.

**Comment by jessepearson** [comment]
Both Bookings 1.10.0 and Accommodations 1.0.8 should work with 2.6.14 without any issue, and they will both also work with 3.0.2 without issue. You should both update either through the Helper or by downloading from your WooCommerce.com dashboard. 

If you'd like to test on a staging site and your host doesn't have that option, try [WP Staging](https://wordpress.org/plugins/wp-staging/), which will make a copy for you to test with.

**Comment by bor0** [comment]
This issue was fixed in the sense that it will not cause fatal errors, as to allow users to update Bookings. Note that you do need to use Bookings >= 1.10.0 with WC 3.0 due to the compat fixes.

**Comment by jessepearson** [comment]
And since Accomm piggy backs off of Bookings, Accomm 1.0.8+ will only work with Bookings 1.10.0+ due to the internal changes needed within them both to make them compatible with WooCommerce 3.0.
