### ISSUE TITLE
Resource Costs not added Custom Rate - Date Ranges

### ISSUE THREAD

**Issue by djcowan** [woocommerce/woocommerce-accommodation-bookings#141]
#### What I expected

Expected Resource costs to be added to Dates with Custom Date Range Prices

#### What happened instead

Resource costs are added to dates with no Custom Date Rage Price but are seemingly ignored on dates with prices adjustments

#### Steps to reproduce the issue

Create > Accommodation Booking Product
Enable > Resources && People
Set > Standard room rate
Set > Person Types
Set > Custom Date Range Rate (range of nights…)
Set > Custom Rate Cost
Create > Resources (x3)
Assign Resources to Product
Set > Resource block costs -> with or without base cost 

Screen shots of associated WC Product Data Tabs.

<img width="1188" alt="custom rate - date range" src="https://user-images.githubusercontent.com/2137698/29969083-e1b408c8-8f61-11e7-9f58-8f045b0d7156.png">
<img width="1183" alt="general" src="https://user-images.githubusercontent.com/2137698/29969080-dfd4c1dc-8f61-11e7-8d8f-b39ce8e0f5fa.png">
<img width="1189" alt="persons" src="https://user-images.githubusercontent.com/2137698/29969079-df99354a-8f61-11e7-9cdf-734f1fe98be8.png">
<img width="1182" alt="resources" src="https://user-images.githubusercontent.com/2137698/29969081-dfde6caa-8f61-11e7-89b2-918e9a960d5d.png">

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by jessepearson** [comment]
Confirmed this is an issue. If a range has a different cost, and resources have defined costs, the resource cost is not added in the range. 

1. Import: [booking-product-10751-2017-09-01.json.zip](https://github.com/woocommerce/woocommerce-accommodation-bookings/files/1270433/booking-product-10751-2017-09-01.json.zip)
1. Select a range of Mon-Thurs, then select Five Cabins
1. Price will adjust properly ✅ 
1. Select a range of Fri-Sun
1. Price does not include resource block pricing ❌

**Comment by LaurenaRehbein** [comment]
Another report of this here: 948306-zen

**Comment by DanielSantoro** [comment]
Any updates on this one? Customer is still waiting in the ticket above.

**Comment by laurendavissmith** [comment]
No ETA yet but I've added it to my list

**Comment by conschneider** [comment]
Got another one: https://woothemes.zendesk.com/agent/tickets/986573

**Comment by bor0** [comment]
The way this is architectured is a bit problematic. When prices are entered in the rates, they are entered in the database under the meta `_wc_booking_pricing`, and the rule has `override` set to it. That means any additional calculations done by Bookings (based either on resources or persons) will be simply overriden by what we enter here.

So when we calculate costs within `WC_Booking_Form::calculate_booking_cost`, at [this line](https://github.com/woocommerce/woocommerce-bookings/blob/0dbb05b/includes/booking-form/class-wc-booking-form.php#L856) `$block_cost` is properly calculated to be 1300, however, given the definition of the rule, it will overwrite any calculations with 1160.

Here is a definition of one simple rule:
```
Array
(
    [base] => Array
        (
            [0] => plus
            [1] => 0
        )

    [block] => Array
        (
            [0] => plus
            [1] => 0
        )

    [override] => 1160
)
```

I believe the best way to fix this issue is to avoid using `override` and use the plus/minus calculations in `base` and `block` [here](https://github.com/woocommerce/woocommerce-accommodation-bookings/blob/97e8abf/includes/admin/class-wc-accommodation-booking-admin-panels.php#L284-L287).

**Comment by laurendavissmith** [comment]
@bor0 Making a note here that we need to provide an update script as part of the PR
