### ISSUE TITLE
rate calculations incorrect

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-accommodation-bookings#170]
#### Affected ticket(s)
reported in live chat  - no ticket

#### What I expected
For my rates to be calculated as per the product configuration (and as they were in 1.1.2)

#### What happened instead
Rates are not calculated correctly as configured

#### Steps to reproduce the issue
1. Import this product
[booking-product-6775-2018-02-02.zip](https://github.com/woocommerce/woocommerce-accommodation-bookings/files/1689543/booking-product-6775-2018-02-02.zip)
2. Select some dates like so:
![see screen shot](http://cld.wthms.co/7QUYvB+)
3. Expected total there is 720 - as was the case under the same conditions with version 1.1.2 as seen here:
![see screen shot](http://cld.wthms.co/cq3Bn4+)

-------------------

- [ ] Issue assigned to next milestone.
- [x] Issue assigned a priority (will be assessed by maintainers).

**Comment by DustinHartzler** [comment]
Some more details with this configuration:

Adult: $104 per night
Child: $77 per night

Here's the product I'm testing:
[booking-product-198-2018-03-20.zip](https://github.com/woocommerce/woocommerce-accommodation-bookings/files/1830048/booking-product-198-2018-03-20.zip)

*For these prices to work out, I had to enter a block cost of $52, instead of $104, which doesn't make sense, but would allow the 2 nights for 2 adults calculation to be correct. Even though the block costs are entered as half the amount they should be, when an additional person type is added, the price, is WAY too high.*

### Change Quantity of People
When you select 2 nights for 2 adults, the price is correct at $416
<img width="456" alt="screen shot 2018-03-20 at 11 39 24 am" src="https://user-images.githubusercontent.com/2293077/37665423-9d0d44a4-2c33-11e8-9859-ba68ffb1d95f.png">

But when I add an additional child ($77 per night) for the same 2 nights with 2 adults it jumps to $1086 instead of $581:
<img width="441" alt="screen shot 2018-03-20 at 11 39 56 am" src="https://user-images.githubusercontent.com/2293077/37665429-a12a9848-2c33-11e8-86c2-149ff8ba589f.png">

Any assistance would be great!

**Comment by DustinHartzler** [comment]
@LaurenaRehbein Is it possible to get some eyes on this? I tried helping setting up a WooCierge client and the inaccurate calculations are not making us look good in their eyes.

**Comment by laurendavissmith** [comment]
@DustinHartzler Added to our triage queue

**Comment by DustinHartzler** [comment]
@laurendavissmith - Any idea when this might get a look. Sorry for pestering :)

**Comment by laurendavissmith** [comment]
@DustinHartzler I've still got it on our triage queue but it will be after we get past GDPR so not until at least the end of May before we'll have a chance to take a look

**Comment by dromero20** [comment]
@laurendavissmith Sorry for bugging you again :) Any idea when you would have the time to take a look into this? Just for updating the client (he came back today).

**Comment by roykho** [comment]
This was discussed in our triage meeting and we have a possible solution for this. To be done by the janitor.

**Comment by bor0** [comment]
So here's the math for your example @DustinHartzler:

Adult = 104
Child = 77

2 x Adult per 2 nights = 104 x 2 = 208 (subtotal cost)

Since `Multiply all costs by person count` is ticked, we multiply 208 by 2 to get 416.

Now, if we add 1 child, here's the math:
2 x Adult + 1 x Child per 2 nights = 2 x 104 + 1 x 77 = 285 (subtotal cost)

Since `Multiply all costs by person count` is ticked, we multiply 285 by 3 to get 855.

I'm not sure if we want to change the way this calculation works.

cc @jessepearson for any additional thoughts.

**Comment by jessepearson** [comment]
It seems that the example from @WillBrubaker is missing persons, so I don't get the same results.
The example from @DustinHartzler seems correct, though, according to @bor0 's calculations. 

The *Multiply all costs* checkbox confuses people and causes issues. It will literally take all costs, then multiply those costs against the number of persons for the booking. I believe it existed to be used with base/block costs for the booking itself, not per person costs.

**Comment by DustinHartzler** [comment]
Ah, the _Multiply All Costs_ checkbox is misleading. Unchecking that box seems to make the calculation work correctly.

**Comment by bor0** [comment]
@jessepearson the particular logic for multiplication is here:
https://github.com/woocommerce/woocommerce-bookings/blame/241857cc0d192399638424b7ccd23ed3b60ace66/includes/booking-form/class-wc-booking-form.php#L930

It seems like it hasn't changed for 4+ years (unless affected by some filter/action, which isn't as far as I checked)

**Comment by jessepearson** [comment]
@bor0 Correct, I didn't mean there was a problem with the calculation, I just meant that the purpose of the box is confusing to customers and they tend to not realize exactly what it does. I remember working on a similar issue in the past and I went over it bit by bit, and it works correctly.

I believe this is the case with Dustin's example, but I am not sure with Will's since the import didn't work correctly.

**Comment by bor0** [comment]
Thank you @jessepearson, this is very helpful. I think it's safe to close this issue for now, but feel free to create a new one (Technical Debt) if we feel that the logic needs to be updated.
