### ISSUE TITLE
Fatal error with PHP 8.0.xx when Base Cost/Block Cost is empty while adding a resource in Accommodation Product

### ISSUE THREAD

**Issue by kaushikasomaiya** [woocommerce/woocommerce-accommodation-bookings#290]
#### Affected ticket(s)

4806348-zen

#### What I expected

The product should be published or updated.

#### What happened instead

but it throws a fatal error: https://d.pr/i/ZADeQd

#### Steps to reproduce the issue

**Make sure the website is on PHP 8.0.xx before testing**

1) Try publishing a new Accommodation product with only WooCommerce, WC Bookings, and Accommodation Bookings plugins as active.
2) Add new product > Select Type as **Accommodation Product**
3) Tick mark the "Has Resources" option and add a resource.
4) Keep one of the values for Base Cost or Block Cost as empty
5) Publish the product -> Results into WP critical error.

Error log:

`2022-02-25T06:48:08+00:00 CRITICAL Uncaught TypeError: Unsupported operand types: string + string in /var/web/staging/public_html/wp-content/plugins/woocommerce-accommodation-bookings/includes/admin/class-wc-accommodation-booking-admin-panels.php:261`

Seems like a known issue with PHP 8.0 when we try to add blank items in array:

`if ( ( $resource_base_cost[ $i ] + $resource_block_cost[ $i ] ) > 0 ) {`

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by ankitguptaindia** [comment]
+1 
I am able to reproduce this on my `Latest` test environment.

**Comment by selectedselections** [comment]
4910670-zen

**Comment by ankitguptaindia** [comment]
**Update -**  Above issues have been fixed with connected PR. New customers' reports of this issue can be tested/verify with this **Dev version** of the Booking plugin.

[woocommerce-accommodation-bookings.zip](https://github.com/woocommerce/woocommerce-accommodation-bookings/files/8787431/woocommerce-accommodation-bookings.zip)



**_Please Note that this is the Dev version of the plugin file and ONLY has fixes related to above issue so other fixes might not work with this dev version of the plugin. It is also recommended that, Don't use this plugin file on the Production/Live site. This is just for testing purposes only_**
