### ISSUE TITLE
Accommodation bookings check against minutes instead of days

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-accommodation-bookings#89]
As mentioned in [this PR](https://github.com/woocommerce/woocommerce-bookings/pull/972), when Bookings is getting blocks in a range, the default is for minutes and this is what Accommodations winds up using instead of *days*. 

As discussed in the PR, this probably wasn't the best route, just an easy fix. Accommodations should override this method within its own code as a solution. 

#### Affected ticket(s) and bug reports

521437-zd-woothemes - in [Bookings PR 972](https://github.com/woocommerce/woocommerce-bookings/pull/972)
515068-zd-woothemes - in [Bookings issue 971](https://github.com/woocommerce/woocommerce-bookings/issues/971)
Accommodations issue #85 

@WillBrubaker added:
522866-zd-woothemes
#### What I expected

Accommodations' `duration_unit` of *night* to be treated the same as Bookings' `duration_unit` of *day*.

#### What happened instead

Accommodations' `duration_unit` of *night* is treated as minutes, so either memory is fully consumed or time outs happen at the server level.

#### Steps to reproduce the issue

See listed issues.

-------------------

- [x] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by MCKLtech** [comment]
I have done some testing on WebGrind and Dynatrace, some of my analysis is here: https://wordpress.org/support/topic/really-slow-product-page-loading/#post-8816514

This issue is very serious as the entire accommodation plugin is inherently flawed by it. There is absolutely no need to checking by the minute for accommodation, I'd even go as far to say there should be no checking by the hour either unless its the check in / check out day.

Unfortunately I'm just not versed enough in the construction of it, but from my basic review, I'd see the following as a possible fix:

- If an accommodation product has only one quantity e.g. An apartment that is either booked or not, it can't have multiple bookings per day, a check by the hour for the first day is probably needed to allow for the check-in. After this, each day should be checked and if it has no availability, we can skip to the next day immediately e.g By day.

In essence, create a hybrid of checking by hour/minute for the first and last day, but everything in-between we can probably treat as a day.

**Comment by bor0** [comment]
@jessepearson is this still an issue? It seems to have been fixed according to https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/85#issuecomment-294208772.

**Comment by jessepearson** [comment]
@bor0 Yup, it no longer does this.
